### ISSUE TITLE
Tracking leaflet marker, Clusterize group of markers

### ISSUE THREAD

**Issue by YummyTi** [alexandra-c/leaflet-tracking-marker#15]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I want to render more than 1000 markers on the map, and being violation issue and slow, that is why please update for this feature

**Describe alternatives you've considered**

**Additional context**

**Comment by alexandra-c** [comment]
I'm sorry but I don't quite understand what's the issue here, if you can please give more info about the issue...
