### ISSUE TITLE
add support to react 18 on peerDependencies

### ISSUE THREAD

**Issue by vitoladev** [alexandra-c/leaflet-tracking-marker#19]
https://github.com/alexandra-c/leaflet-tracking-marker/blob/85b0940b688d76d291c027d30ef0add062508eb6/package.json#L42

**Comment by alexandra-c** [comment]
Hello, @vitoladev,
I will add support for react 18 today.  
If you wish, maybe next time you can also contribute with a PR to get it fixed faster. 
Thanks 😊
