### ISSUE TITLE
Rotation Angle Zero doesn't work on marker update

### ISSUE THREAD

**Issue by FernandoI7** [alexandra-c/leaflet-tracking-marker#24]
**Describe the bug**
When a marker is defined with `rotationAngle` equal to zero, after updating, the marker does not use the zero value and updates the marker angle considering the position variation.

**To Reproduce**
1. Setup a marker with `rotationAngle={0}`
```
import { useEffect, useState } from "react";
import { LeafletTrackingMarker } from "react-leaflet-tracking-marker/src";
import PropTypes from "prop-types";

const AnimatedMarker = ({ icon, latitude, longitude, children }) => {
  const [prevPos, setPrevPos] = useState([latitude, longitude]);

  useEffect(() => {
    if (prevPos[1] !== longitude && prevPos[0] !== latitude)
      setPrevPos([latitude, longitude]);
  }, [latitude, longitude, prevPos]);

  return (
    <LeafletTrackingMarker
      icon={icon}
      position={[latitude, longitude]}
      duration={1000}
      rotationAngle={0}
      rotationOrigin="unset"
    >
      {children}
    </LeafletTrackingMarker>
  );
};

AnimatedMarker.propTypes = {
  icon: PropTypes.object.isRequired,
  latitude: PropTypes.number.isRequired,
  longitude: PropTypes.number.isRequired,
  children: PropTypes.object.isRequired,
};

export default AnimatedMarker;
```
2. Update the marker position

**Expected behaviour**
Marker must keep zero angle even after marker position update

**Screenshots**
![screencast-localhost_3000-2022 08 23-15_26_28](https://user-images.githubusercontent.com/1686120/186236228-258d5628-1253-4c7b-9dfe-91d9efb4724c.gif)

I already opened a pull request fixing the problem https://github.com/alexandra-c/leaflet-tracking-marker/pull/23

**Comment by alexandra-c** [comment]
Hello, @FernandoI7 ,
I approved and merged your fix, and will create a new release.
Thank you for contributing!
