### ISSUE TITLE
Error when npm run build, in nextjs (typescript)

### ISSUE THREAD

**Issue by galaxiarmy** [alexandra-c/leaflet-tracking-marker#26]
Version:
node  : v18.7.0
npm  : 8.15.0
react version : 17.0.2
react-leaflet : 3.2.0
leaflet : 1.7.1
react-leaflet-tracking-marker : 1.0.15

Hello good morning, i have some problem when,  i build the application, when i use "npm run build" in nextjs, previously there was no error, when i build,  can you help me? thank you

<img width="936" alt="Screen Shot 2022-09-23 at 08 09 17" src="https://user-images.githubusercontent.com/50814369/191876565-f894dd75-47a8-48d4-b412-9cdc1a666275.png">

**Comment by galaxiarmy** [comment]
can you respond sir?

**Comment by alexandra-c** [comment]
Hello, I'm not sure what the problem might be, can you provide a reproduction code in Code Sandbox or something else? 
As a first glance, for me it seems like some package or ad-on might be missing...

**Comment by galaxiarmy** [comment]
I try, still error above

**Comment by galaxiarmy** [comment]
Sorry, if my english is bad, i see, after i tracing this issue, i know this case, i will information this, step by step:

1. I have repository with library **"react-leaflet-tracking-marker"**, with version : **1.0.11**
   
<img width="416" alt="Screen Shot 2022-09-28 at 14 43 23" src="https://user-images.githubusercontent.com/50814369/192719696-43571a68-8473-49e8-a585-8b0a3a5018a4.png">

2. after, first time, i fresh clone in this repository, and npm install,
    
<img width="392" alt="Screen Shot 2022-09-28 at 14 28 17" src="https://user-images.githubusercontent.com/50814369/192720574-b6ced71d-6f51-4ad7-bb74-a1a3625572fa.png">

3. i look at folder node_modules/react-leaflet-tracking-marker/index.d.ts
    and i found case with typescript, i think this library, i install is latest version (1.0.15),
   not my previous library, with version 1.0.11
  
<img width="1038" alt="Screen Shot 2022-09-28 at 14 28 51" src="https://user-images.githubusercontent.com/50814369/192722160-fe77e6df-1a77-4d43-9508-02d7931c5b11.png">

4. And, I look to folder node_modules/react-leaflet-tracking-marker/package.json
    and i found, library, i use is latest version (1.0.15).
    not my previous library, with version 1.0.11

<img width="935" alt="Screen Shot 2022-09-28 at 15 33 23" src="https://user-images.githubusercontent.com/50814369/192731331-9fd18bdd-3204-4948-8733-a4b23d92194a.png">

5. when, npm run build, i found this error
    
<img width="838" alt="Screen Shot 2022-09-27 at 15 44 22" src="https://user-images.githubusercontent.com/50814369/192733445-9b0f6dcf-d7f4-4b10-9d1a-ada5b8c56524.png">

6. Now, i know this error, because i use library with latest version (1.0.15), 
   not my previous library with version 1.0.11, when i, npm uninstall this library and change npm install 
   with spesific version "npm install react-leaflet-tracking-marker@1.0.11"
   I not found this issue, and npm run build is success

<img width="707" alt="Screen Shot 2022-09-28 at 15 52 39" src="https://user-images.githubusercontent.com/50814369/192736864-18c2de11-4898-4ff1-b2ca-bbffe5ab0d94.png">

Issues:
-when first clone repository with library react-leaflet-tracking-marker, and npm install, we get latest version (1.0.15), 
  not my previous version in my package.json (1.0.11)

Solved:
-we need to, when I, npm install, i get my previous version (1.0.11), in my node_modules and package.json,
  not latest version (1.0.15)

Question:
-can i solved this, issue?

Thank you sir, if you response

**Comment by alexandra-c** [comment]
Hello, 

First, I am a woman.. not a 'sir" 😁
If you want to install a certain version of a package you have to change your package.json dependency to the specific version without "^" like this "react-leaflet-tracking-marker" :"1.0.11" ... please read npm documentation and how semantic versioning work... https://nodejs.dev/en/learn/semantic-versioning-using-npm/

**Comment by galaxiarmy** [comment]
thank you, alexandra for your response after this issue hehe...this work...sory if i often talkative
