### ISSUE TITLE
Problem with KeepAtCenter

### ISSUE THREAD

**Issue by Dhinesh-Dhinesh** [alexandra-c/leaflet-tracking-marker#28]
I am trying to toggle keepAtCenter but it's not working, Stucked on the marker position  i can't move the map

here is my code:
```
const [isTracking,setIsTracking] = useState(false)

<LeafletTrackingMarker position={....} icon={....} duration={1000} rotationAngle={...} rotationOrigin="center" keepAtCenter={isTrack}> 
  <Popup>
     Sample Bus Data & Speed:{bus.data.data.speed}
  </Popup>
</LeafletTrackingMarker>

 ..... onClick() {
  setIsTracking((prev)=>!prev)
}
```

**Comment by alexandra-c** [comment]
Hello, 
I'm afraid this is not an issue. The `keepAtCenter` function works as it is supposed to.  As stated in the documentation, this library was inspired from [leaflet-drift-marker](https://github.com/hugobarragon/leaflet-drift-marker#drift_marker-with-leaflet) and [react-leaflet-rotatedmarker](https://github.com/verdie-g/react-leaflet-rotatedmarker). You can also check out their documentation examples, I suggest this one here https://codesandbox.io/s/react-leaflet-drift-markerv3-nxzht?fontsize=14&hidenavigation=1&theme=dark&file=/src/index.js , the newer version of leaflet-drift-marker library.
